apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-demo-mysql-pv
spec:
  storageClassName: k8s-demo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
